### ISSUE TITLE
Front-End Dev II

### ISSUE THREAD

**Issue by feliphebueno** [GrupoBRA/jobs#20]
Temos vagas em aberto para desenvolvedores e desenvolvedoras Front-End

### Avançado:
   - [ ] Javascript(front-end only);
   - [ ] Conhecimento em [VueJS](https://vuejs.org/) ou framework similar(Angular/React);
   - [ ] HTML;
   - [ ] CSS/CSS3;
   - [ ] Material Design;
   - [ ] Desenvolvimento de UI responsiva;

### Básico:
   - [ ] Git;
   - [ ] AJAX;
   - [ ] Morar na região metropolitana de Recife;

### Diferenciais

   - [ ] Experiência com integrações front-end -> back-end;
   - [ ] Desenvolvimento de SPAs;
   - [ ] Experiência com PWA;
   - [ ] Alguma experiência em desenvolvimento mobile com tecnologias web;
   - [ ] Inglês intermediário ou fluente

### Como se candidatar
Como domínio do Git é uma obrigatoriedade para trabalhar com a gente, se você tem interesse em uma das vagas, clone este repositório, anexe o seu currículo na raiz faça um commit e push para uma branch com o seu {nome_sobrenome}. Em seguida, faça um pull-request da sua branch para a branch master. A partir daí é com a gente!

Não recebemos currículo de outra forma.

### Regime de contratação
Pessoa Jurídica;

### Faixa de remuneração
Acima da média de mercado

### Sobre a BRA Consultoria
A [BRA Consultoria](http://www.grupobra.com) é hoje o maior player em market share no segmento de Regimes Próprios de Previdência Social, atendendo a mais de uma centena de institutos de previdência social, prefeituras e câmaras de vereadores no país inteiro. Parece complicado né? mas fique tranquilo, nós temos um programa de capacitação interna com cursos onde você poderá se inteirar melhor sobre o assunto. Nossa unidade de desenvolvimento fica em Olinda, Pernambuco, no bairro Jardim Atlântico.

### Coisas interessantes sobre nós

- Trabalhamos apenas com o que há de mais inovador em tecnologia, tanto no desenvolvimento em si, quanto na parte de infraestrutura;
- Desenvolvedores back-end codificam em Python, front-end em Javascript, cada um no seu quadrado;
- Todas as back-end apps são APIs REST que recebem e retornam apenas dados;
- Todas as front-end apps são SPAs/PWAs em HTML/CSS/JS;
- Abolimos o banco relacional; um salve para o MongoDB!
- Nosso modelo data center é de computação distribuída;
- Nossa arquitetura de desenvolvimento é em micro-API's de microservices;
- Se é possível fazer melhor, faça melhor!

**Comment by ViniciusPuerto** [comment]
Olá, boa noite.
A vaga é apenas para residentes de Recife?

**Comment by feliphebueno** [comment]
Boa noite, @ViniciusPuerto.

A vaga é para a modalidade presencial(exceto neste período de lockdown), nesse caso você teria que ter o interesse e disponibilidade pra se mudar pra região metropolitana de Recife, porém nós pretendemos realizar a entrevista de forma presencial, então você precisaria já estar por aqui pra participar do processo. Mas mande seu currículo, vamos conversar, assim podemos tirar melhor todas as dúvidas.

**Comment by ViniciusPuerto** [comment]
Beleza @feliphebueno , vou abrir um PR. Obrigado.

**Comment by LucianoNascimento** [comment]
Bom dia, Curriculo enviado

**Comment by Dagmar87** [comment]
[JOSE DAGMAR FSS CV - EngComp.pdf](https://github.com/GrupoBRA/jobs/files/4518572/JOSE.DAGMAR.FSS.CV.-.EngComp.pdf)

**Comment by feliphebueno** [comment]
@Dagmar87 O seu comentário foi removido a fim de mantermos a isonomia do processo. Instruções sobre a única forma possível para o envio de currículos estão na descrição principal desta issue.

**Comment by messiasdias** [comment]
Tem alguma data previamente marcada para a entrevista, ou temos que aguardar o fim do período da quarentena pra saber mais?

**Comment by feliphebueno** [comment]
Boa tarde, @messiasdias.

Ainda esta semana iniciaremos a segunda fase do processo seletivo, entraremos em contato com os candidatos cujo o perfil curricular esteja mais próximo do descrito acima, independentemente de ter sido selecionado ou não, todos os participantes receberão o feedback diretamente em seus respectivos pull requests ao fim desta fase(15/05).

**Comment by jzrbsv** [comment]
Vaga ainda aberta, @feliphebueno?

**Comment by feliphebueno** [comment]
Bom dia @betodasilva, temos uma vaga em aberto ainda, mande o seu PR pra participar.

**Comment by rebeccamanzi** [comment]
Olá! Fiz o PR, aguardando o feedback.

**Comment by feliphebueno** [comment]
Boa tarde a todos.


Informo que a fase de recebimento de currículos para esta vaga está encerrada e o RH enviará um email de feedback a todos os participantes. 


Agradeço a todos que se candidataram.

**Comment by Dagmar87** [comment]
Vcs tem o passo a passo de colocar o curriculo no github para iniciantes pela primeira vez ???
