### ISSUE TITLE
Permissão Negada 

### ISSUE THREAD

**Issue by isaacam517** [GrupoBRA/jobs#36]
Olá, tudo bem? estou tentanto fazer o push mas está retornando erro 403.

remote: Permission to GrupoBRA/jobs.git denied to isaacam517.
fatal: unable to access 'https://github.com/GrupoBRA/jobs.git/': The requested URL returned error: 403

**Comment by 4ndr** [comment]
> Olá, tudo bem? estou tentanto fazer o push mas está retornando erro 403.
> 
> remote: Permission to GrupoBRA/jobs.git denied to isaacam517.
> fatal: unable to access 'https://github.com/GrupoBRA/jobs.git/': The requested URL returned error: 403

Oi @isaacam517, 
Você já verificou se está fazendo o procedimento correto?

**Comment by isaacam517** [comment]
Sim, agora foi. vlw!
